src/main/java/com/gerenciamento/contabil/models/Role.java
package com.gerenciamento.contabil.models;

import javax.persistence.Entity;
import javax.persistence.Id;

import org.springframework.security.core.GrantedAuthority;

@Entity
public class Role implements GrantedAuthority{
	 
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	private String name;
	
	private String description;

	@Override
	public String getAuthority() {
	
		return name;
	}
	
	public void setRole(String papel){
		this.name = papel;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}

src/main/java/com/gerenciamento/contabil/models/User.java
package com.gerenciamento.contabil.models;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;

@Entity
@NamedQueries({ @NamedQuery(name = "User.buscarPorEmail", query = "SELECT e FROM User e WHERE e.login = :email") })
public class User implements UserDetails {

	private static final long serialVersionUID = 1L;

	@Id
	private String login;
	private String password;
	private String name;

	@ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.REFRESH)
	private List<Role> roles = new ArrayList<>();

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		return getRoles();
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return password;
	}

	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return login;
	}

	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public static User getUserLogged() {

		User user = null;

		// check if user is login
		Authentication auth = SecurityContextHolder.getContext()
				.getAuthentication();
		if (!(auth instanceof AnonymousAuthenticationToken)) {
			UserDetails userDetail = (UserDetails) auth.getPrincipal();

			user = (User) userDetail;

		}

		return user;

	}

}

src/main/java/com/gerenciamento/contabil/controller/CalendarController.java
package com.gerenciamento.contabil.controller;

import javax.transaction.Transactional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.gerenciamento.contabil.daos.EventsDAO;
import com.gerenciamento.contabil.models.Events;
import com.gerenciamento.contabil.models.User;
import com.gerenciamento.contabil.util.DateStartEnd;

@Controller
@Transactional
@RequestMapping("/calendar")
public class CalendarController {
	
	private static final Logger logger = LoggerFactory.getLogger(CalendarController.class);
	
	@Autowired
	EventsDAO eventsDao;
	
	
	@RequestMapping(method=RequestMethod.GET)
	public ModelAndView home(Events events){
		ModelAndView modelAndView = new ModelAndView("calendar/calendar");
		return modelAndView;
	}
	
	@RequestMapping(value="/update", method=RequestMethod.POST)
	public String update(Events events){
		events.setUser(new User());
		
		eventsDao.update(events);
		return "home";
	}
	
	@RequestMapping(value="/delete/{id}")
	public ModelAndView delete(@PathVariable Long id){
		eventsDao.delete(eventsDao.findById(id));
		ModelAndView modelAndView = new ModelAndView("home");
		return modelAndView;
	}
	
	@RequestMapping(value="/find/{id}", method=RequestMethod.GET)
	public ModelAndView findUser(@PathVariable Long id){
		Events events = eventsDao.findById(id);
		ModelAndView modelAndView = new ModelAndView("home");
		modelAndView.addObject("event", events);
		return modelAndView;
		
	}
	
	@RequestMapping(method=RequestMethod.POST)
	public ModelAndView save(Events events){
		
		events.setUser(new User());
		
		eventsDao.save(events);
		ModelAndView modelAndView = new ModelAndView("home");
		return modelAndView;
	}
	
	@RequestMapping(value = "/list", method= RequestMethod.GET)
	public ModelAndView list(DateStartEnd date){
		
		ModelAndView modelAndView = new ModelAndView("home");
		modelAndView.addObject("events", eventsDao.findByDate(date, User.getUserLogged()));
		return modelAndView;
	}

}

src/main/webapp/WEB-INF/views/calendar/calendar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> -->
<!DOCTYPE html>

<html>
	<head>
	<meta charset="UTF-8" >
        <link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/calendar/fullcalendar.min.css"/>" />
        
		<link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/calendar/bootstrap-colorpicker.min.css"/>" />
		<link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/calendar/bootstrap-timepicker.min.css"/>" />
        
        
        <script src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment.min.js'></script>
        
        <script src="<c:url value="/resources/js/calendar/bootstrap-timepicker.min.js"/>"></script>
        <script src="<c:url value="/resources/js/calendar/fullcalendar.min.js"/>"></script>
        <script src="<c:url value="/resources/js/calendar/lang-all.js"/>"></script>
        <script src="<c:url value="/resources/js/calendar/bootstrapValidator.min.js"/>"></script>
        
        <script src="<c:url value="/resources/js/calendar/bootstrap-colorpicker.min.js"/>"></script>
        <script src="<c:url value="/resources/js/calendar/bootstrap-timepicker.min.js"/>"></script>
        <script src="<c:url value="/resources/js/calendar/main.js"/>"></script>
    </head>
    <body>
    	<script src="<c:url value="/resources/js/validation/jquery.validate.js"/>"></script>
		<script src="<c:url value="/resources/js/validation/util.validate.js"/>"></script>
		
		<script type="text/javascript">
		
		$(document).ready( function() {
			  $("#crud-form").validate({
			    // Define as regras
			    rules:{
			      title:{
			        // campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
			        required: true
			      },
			      time:{
			        // campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
			        required: true
			      },
			      EndTime:{
				       
				        required: true
				      },
			      description:{
			        required: true
			      },

			     
			      
			      
			    },
			    // Define as mensagens de erro para cada regra
			    messages:{
			      title:{
			        required: "Digite um título",
			      },
			     time:{
			        required: "Escolha uma data inicial",
			      },
			      EndTime:{
			        required: "Escolha uma data final",
			      },
			      description:{
				        required: "Digite uma descrição",
				      },
   
			     
			    }
			  });
			});
		
		</script>
    	<input type="hidden" name="token" id="idtoken" value="${_csrf.token}"/>
            <div class="row_calendar clearfix">
                <div class="column">
                        <div id='calendar'></div>
                </div>
            </div>
        <div class="modal fade" id="modalCalendar">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                        <div class="error"></div>
                        <form class="form-horizontal" id="crud-form">
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="title">Titulo:</label>
                                <div class="col-md-4">
                                    <input id="title" name="title" type="text" class="form-control input-md" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="time">Horario Inicial:</label>
                                <div class="col-md-4 input-append bootstrap-timepicker">
                                    <input id="time" name="time" type="time" class="form-control input-md" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="time">Horário final:</label>
                                <div class="col-md-4 input-append bootstrap-timepicker">
                                    <input id="idEndTime" name="EndTime" type="time" class="form-control input-md" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="description">Descrição:</label>
                                <div class="col-md-4">
                                    <textarea class="form-control" id="description" name="description"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="color">Cor:</label>
                                <div class="col-md-4">
                                    <input id="color" name="color" type="color" class="form-control input-md" readonly="readonly" />
                                    <span class="help-block">Clique para escolher a cor.</span>
                                </div>
                            </div>
							
							<sec:authorize access="hasRole('ADMIN')">                            
	                            <div class="form-group">
	                                <label class="col-md-4 control-label" for="group1">Evento:</label>
	                                <div class="col-md-4">
	                                    <input type="radio" id="idgroup1" name="group1" value="Y"> Público<br>
										<input type="radio" id="idgroup1" name="group1" value="N" checked> Privado
	                                </div>
	                            </div>
                            </sec:authorize>
                        </form>
                    </div>
                    
                    <div class="modal-footer" id="modalFooterCalendar">
                         <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                    
                    <sec:authorize access="isAuthenticated()">
						<sec:authentication property="principal" var="userCalendar" />
						<input type="hidden" name="userRole" id="idUserRole" value="${userCalendar.authorities[0].authority}"/>
					</sec:authorize>
                </div>
            </div>
        </div>
    </body>
</html>